//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp3.localhostGrc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GerenciaSoap", Namespace="http://tempuri.org/")]
    public partial class Gerencia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AprovarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReprovarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaVendedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaDadosOrcamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Gerencia() {
            this.Url = global::WindowsFormsApp3.Properties.Settings.Default.WindowsFormsApp3_localhostGrc_Gerencia;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AprovarCompletedEventHandler AprovarCompleted;
        
        /// <remarks/>
        public event ReprovarCompletedEventHandler ReprovarCompleted;
        
        /// <remarks/>
        public event RetornaOrcamentoCompletedEventHandler RetornaOrcamentoCompleted;
        
        /// <remarks/>
        public event RetornaVendedorCompletedEventHandler RetornaVendedorCompleted;
        
        /// <remarks/>
        public event RetornaDadosOrcamentoCompletedEventHandler RetornaDadosOrcamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Aprovar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Aprovar(int IdPedido) {
            object[] results = this.Invoke("Aprovar", new object[] {
                        IdPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AprovarAsync(int IdPedido) {
            this.AprovarAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void AprovarAsync(int IdPedido, object userState) {
            if ((this.AprovarOperationCompleted == null)) {
                this.AprovarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAprovarOperationCompleted);
            }
            this.InvokeAsync("Aprovar", new object[] {
                        IdPedido}, this.AprovarOperationCompleted, userState);
        }
        
        private void OnAprovarOperationCompleted(object arg) {
            if ((this.AprovarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AprovarCompleted(this, new AprovarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reprovar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reprovar(int IdPedido) {
            object[] results = this.Invoke("Reprovar", new object[] {
                        IdPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReprovarAsync(int IdPedido) {
            this.ReprovarAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void ReprovarAsync(int IdPedido, object userState) {
            if ((this.ReprovarOperationCompleted == null)) {
                this.ReprovarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReprovarOperationCompleted);
            }
            this.InvokeAsync("Reprovar", new object[] {
                        IdPedido}, this.ReprovarOperationCompleted, userState);
        }
        
        private void OnReprovarOperationCompleted(object arg) {
            if ((this.ReprovarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReprovarCompleted(this, new ReprovarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaOrcamentos", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ORCAMENTO", IsNullable=false)]
        public Orcamento[] RetornaOrcamento() {
            object[] results = this.Invoke("RetornaOrcamento", new object[0]);
            return ((Orcamento[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaOrcamentoAsync() {
            this.RetornaOrcamentoAsync(null);
        }
        
        /// <remarks/>
        public void RetornaOrcamentoAsync(object userState) {
            if ((this.RetornaOrcamentoOperationCompleted == null)) {
                this.RetornaOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaOrcamentoOperationCompleted);
            }
            this.InvokeAsync("RetornaOrcamento", new object[0], this.RetornaOrcamentoOperationCompleted, userState);
        }
        
        private void OnRetornaOrcamentoOperationCompleted(object arg) {
            if ((this.RetornaOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaOrcamentoCompleted(this, new RetornaOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaVendedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornaVendedor(int IdVendedor) {
            object[] results = this.Invoke("RetornaVendedor", new object[] {
                        IdVendedor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornaVendedorAsync(int IdVendedor) {
            this.RetornaVendedorAsync(IdVendedor, null);
        }
        
        /// <remarks/>
        public void RetornaVendedorAsync(int IdVendedor, object userState) {
            if ((this.RetornaVendedorOperationCompleted == null)) {
                this.RetornaVendedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaVendedorOperationCompleted);
            }
            this.InvokeAsync("RetornaVendedor", new object[] {
                        IdVendedor}, this.RetornaVendedorOperationCompleted, userState);
        }
        
        private void OnRetornaVendedorOperationCompleted(object arg) {
            if ((this.RetornaVendedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaVendedorCompleted(this, new RetornaVendedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaDadosOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaOrcamentoDados", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ORCAMENTODADOS", IsNullable=false)]
        public OrcamentoDados[] RetornaDadosOrcamento(int IdPedido) {
            object[] results = this.Invoke("RetornaDadosOrcamento", new object[] {
                        IdPedido});
            return ((OrcamentoDados[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaDadosOrcamentoAsync(int IdPedido) {
            this.RetornaDadosOrcamentoAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void RetornaDadosOrcamentoAsync(int IdPedido, object userState) {
            if ((this.RetornaDadosOrcamentoOperationCompleted == null)) {
                this.RetornaDadosOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaDadosOrcamentoOperationCompleted);
            }
            this.InvokeAsync("RetornaDadosOrcamento", new object[] {
                        IdPedido}, this.RetornaDadosOrcamentoOperationCompleted, userState);
        }
        
        private void OnRetornaDadosOrcamentoOperationCompleted(object arg) {
            if ((this.RetornaDadosOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaDadosOrcamentoCompleted(this, new RetornaDadosOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Orcamento {
        
        private int pedidoField;
        
        private string tipoField;
        
        private string dataEmissaoField;
        
        private string observacoesField;
        
        private string vendedorField;
        
        private string prazoEntregaField;
        
        private string condicaoPagField;
        
        private double valorTotalField;
        
        private int qtdItensField;
        
        /// <remarks/>
        public int Pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
            }
        }
        
        /// <remarks/>
        public string PrazoEntrega {
            get {
                return this.prazoEntregaField;
            }
            set {
                this.prazoEntregaField = value;
            }
        }
        
        /// <remarks/>
        public string CondicaoPag {
            get {
                return this.condicaoPagField;
            }
            set {
                this.condicaoPagField = value;
            }
        }
        
        /// <remarks/>
        public double ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public int QtdItens {
            get {
                return this.qtdItensField;
            }
            set {
                this.qtdItensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrcamentoDados {
        
        private string codField;
        
        private string nomeField;
        
        private string unidadeMedidaField;
        
        private double solicitarField;
        
        /// <remarks/>
        public string Cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeMedida {
            get {
                return this.unidadeMedidaField;
            }
            set {
                this.unidadeMedidaField = value;
            }
        }
        
        /// <remarks/>
        public double Solicitar {
            get {
                return this.solicitarField;
            }
            set {
                this.solicitarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AprovarCompletedEventHandler(object sender, AprovarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AprovarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AprovarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReprovarCompletedEventHandler(object sender, ReprovarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReprovarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReprovarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaOrcamentoCompletedEventHandler(object sender, RetornaOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Orcamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Orcamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaVendedorCompletedEventHandler(object sender, RetornaVendedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaVendedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaVendedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaDadosOrcamentoCompletedEventHandler(object sender, RetornaDadosOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaDadosOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaDadosOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrcamentoDados[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrcamentoDados[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591