//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp3.localhostAdm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdminSoap", Namespace="http://tempuri.org/")]
    public partial class Admin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastroUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastroPermissoesUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Admin() {
            this.Url = global::WindowsFormsApp3.Properties.Settings.Default.WindowsFormsApp3_localhostAdm_Admin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastroUsuarioCompletedEventHandler CadastroUsuarioCompleted;
        
        /// <remarks/>
        public event CadastroPermissoesUsuarioCompletedEventHandler CadastroPermissoesUsuarioCompleted;
        
        /// <remarks/>
        public event RetornaUsuarioCompletedEventHandler RetornaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastroUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CadastroUsuario(string Nome, string Funcao, string Departamento, string Usuario, string Senha, System.DateTime DataCriacao) {
            object[] results = this.Invoke("CadastroUsuario", new object[] {
                        Nome,
                        Funcao,
                        Departamento,
                        Usuario,
                        Senha,
                        DataCriacao});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CadastroUsuarioAsync(string Nome, string Funcao, string Departamento, string Usuario, string Senha, System.DateTime DataCriacao) {
            this.CadastroUsuarioAsync(Nome, Funcao, Departamento, Usuario, Senha, DataCriacao, null);
        }
        
        /// <remarks/>
        public void CadastroUsuarioAsync(string Nome, string Funcao, string Departamento, string Usuario, string Senha, System.DateTime DataCriacao, object userState) {
            if ((this.CadastroUsuarioOperationCompleted == null)) {
                this.CadastroUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastroUsuarioOperationCompleted);
            }
            this.InvokeAsync("CadastroUsuario", new object[] {
                        Nome,
                        Funcao,
                        Departamento,
                        Usuario,
                        Senha,
                        DataCriacao}, this.CadastroUsuarioOperationCompleted, userState);
        }
        
        private void OnCadastroUsuarioOperationCompleted(object arg) {
            if ((this.CadastroUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastroUsuarioCompleted(this, new CadastroUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastroPermissoesUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastroPermissoesUsuario(string Departamento, int IdUsuario, string Nome) {
            object[] results = this.Invoke("CadastroPermissoesUsuario", new object[] {
                        Departamento,
                        IdUsuario,
                        Nome});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastroPermissoesUsuarioAsync(string Departamento, int IdUsuario, string Nome) {
            this.CadastroPermissoesUsuarioAsync(Departamento, IdUsuario, Nome, null);
        }
        
        /// <remarks/>
        public void CadastroPermissoesUsuarioAsync(string Departamento, int IdUsuario, string Nome, object userState) {
            if ((this.CadastroPermissoesUsuarioOperationCompleted == null)) {
                this.CadastroPermissoesUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastroPermissoesUsuarioOperationCompleted);
            }
            this.InvokeAsync("CadastroPermissoesUsuario", new object[] {
                        Departamento,
                        IdUsuario,
                        Nome}, this.CadastroPermissoesUsuarioOperationCompleted, userState);
        }
        
        private void OnCadastroPermissoesUsuarioOperationCompleted(object arg) {
            if ((this.CadastroPermissoesUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastroPermissoesUsuarioCompleted(this, new CadastroPermissoesUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaUsuario", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("USUARIO", IsNullable=false)]
        public Usuario[] RetornaUsuario() {
            object[] results = this.Invoke("RetornaUsuario", new object[0]);
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaUsuarioAsync() {
            this.RetornaUsuarioAsync(null);
        }
        
        /// <remarks/>
        public void RetornaUsuarioAsync(object userState) {
            if ((this.RetornaUsuarioOperationCompleted == null)) {
                this.RetornaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaUsuarioOperationCompleted);
            }
            this.InvokeAsync("RetornaUsuario", new object[0], this.RetornaUsuarioOperationCompleted, userState);
        }
        
        private void OnRetornaUsuarioOperationCompleted(object arg) {
            if ((this.RetornaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaUsuarioCompleted(this, new RetornaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string nomeField;
        
        private string funcaoField;
        
        private string departamentoField;
        
        private string userField;
        
        private string dataCriacaoField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Funcao {
            get {
                return this.funcaoField;
            }
            set {
                this.funcaoField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CadastroUsuarioCompletedEventHandler(object sender, CadastroUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastroUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastroUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CadastroPermissoesUsuarioCompletedEventHandler(object sender, CadastroPermissoesUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastroPermissoesUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastroPermissoesUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaUsuarioCompletedEventHandler(object sender, RetornaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591