//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace WindowsFormsApp3.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsSolicitacaoCompraCompleta")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsSolicitacaoCompraCompleta : global::System.Data.DataSet {
        
        private SolicitacaoCompletaDataTable tableSolicitacaoCompleta;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dsSolicitacaoCompraCompleta() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dsSolicitacaoCompraCompleta(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SolicitacaoCompleta"] != null)) {
                    base.Tables.Add(new SolicitacaoCompletaDataTable(ds.Tables["SolicitacaoCompleta"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SolicitacaoCompletaDataTable SolicitacaoCompleta {
            get {
                return this.tableSolicitacaoCompleta;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsSolicitacaoCompraCompleta cln = ((dsSolicitacaoCompraCompleta)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SolicitacaoCompleta"] != null)) {
                    base.Tables.Add(new SolicitacaoCompletaDataTable(ds.Tables["SolicitacaoCompleta"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableSolicitacaoCompleta = ((SolicitacaoCompletaDataTable)(base.Tables["SolicitacaoCompleta"]));
            if ((initTable == true)) {
                if ((this.tableSolicitacaoCompleta != null)) {
                    this.tableSolicitacaoCompleta.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsSolicitacaoCompraCompleta";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsSolicitacaoCompraCompleta.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSolicitacaoCompleta = new SolicitacaoCompletaDataTable();
            base.Tables.Add(this.tableSolicitacaoCompleta);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeSolicitacaoCompleta() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsSolicitacaoCompraCompleta ds = new dsSolicitacaoCompraCompleta();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void SolicitacaoCompletaRowChangeEventHandler(object sender, SolicitacaoCompletaRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SolicitacaoCompletaDataTable : global::System.Data.TypedTableBase<SolicitacaoCompletaRow> {
            
            private global::System.Data.DataColumn columnCod_Produto;
            
            private global::System.Data.DataColumn columnNome_Produto;
            
            private global::System.Data.DataColumn columnQuantidade_Solicitada;
            
            private global::System.Data.DataColumn columnUnidade_De_Medida;
            
            private global::System.Data.DataColumn columnPreco_Unitario;
            
            private global::System.Data.DataColumn columnData_Emissao;
            
            private global::System.Data.DataColumn columnPeriodo_Solicitacao;
            
            private global::System.Data.DataColumn columnPeriodo_Entrega;
            
            private global::System.Data.DataColumn columnCondicao_Pagamento;
            
            private global::System.Data.DataColumn columnTotal;
            
            private global::System.Data.DataColumn columnNomeFornecedor;
            
            private global::System.Data.DataColumn columnCPFFornecedor;
            
            private global::System.Data.DataColumn columnCEPFornecedor;
            
            private global::System.Data.DataColumn columnEnderecoFornecedor;
            
            private global::System.Data.DataColumn columnBairroFornecedor;
            
            private global::System.Data.DataColumn columnCidadeFornecedor;
            
            private global::System.Data.DataColumn columnComplementoFornecedor;
            
            private global::System.Data.DataColumn columnEstadoFornecedor;
            
            private global::System.Data.DataColumn columnComplemento2Fornecedor;
            
            private global::System.Data.DataColumn columnNumeroFornecedor;
            
            private global::System.Data.DataColumn columnTelefoneFornecedor;
            
            private global::System.Data.DataColumn columnTelefone2Fornecedor;
            
            private global::System.Data.DataColumn columnEmailFornecedor;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaDataTable() {
                this.TableName = "SolicitacaoCompleta";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal SolicitacaoCompletaDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected SolicitacaoCompletaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Cod_ProdutoColumn {
                get {
                    return this.columnCod_Produto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Nome_ProdutoColumn {
                get {
                    return this.columnNome_Produto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Quantidade_SolicitadaColumn {
                get {
                    return this.columnQuantidade_Solicitada;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Unidade_De_MedidaColumn {
                get {
                    return this.columnUnidade_De_Medida;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Preco_UnitarioColumn {
                get {
                    return this.columnPreco_Unitario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Data_EmissaoColumn {
                get {
                    return this.columnData_Emissao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Periodo_SolicitacaoColumn {
                get {
                    return this.columnPeriodo_Solicitacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Periodo_EntregaColumn {
                get {
                    return this.columnPeriodo_Entrega;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Condicao_PagamentoColumn {
                get {
                    return this.columnCondicao_Pagamento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TotalColumn {
                get {
                    return this.columnTotal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NomeFornecedorColumn {
                get {
                    return this.columnNomeFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CPFFornecedorColumn {
                get {
                    return this.columnCPFFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CEPFornecedorColumn {
                get {
                    return this.columnCEPFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn EnderecoFornecedorColumn {
                get {
                    return this.columnEnderecoFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn BairroFornecedorColumn {
                get {
                    return this.columnBairroFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn CidadeFornecedorColumn {
                get {
                    return this.columnCidadeFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ComplementoFornecedorColumn {
                get {
                    return this.columnComplementoFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn EstadoFornecedorColumn {
                get {
                    return this.columnEstadoFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Complemento2FornecedorColumn {
                get {
                    return this.columnComplemento2Fornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NumeroFornecedorColumn {
                get {
                    return this.columnNumeroFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TelefoneFornecedorColumn {
                get {
                    return this.columnTelefoneFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn Telefone2FornecedorColumn {
                get {
                    return this.columnTelefone2Fornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn EmailFornecedorColumn {
                get {
                    return this.columnEmailFornecedor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaRow this[int index] {
                get {
                    return ((SolicitacaoCompletaRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event SolicitacaoCompletaRowChangeEventHandler SolicitacaoCompletaRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event SolicitacaoCompletaRowChangeEventHandler SolicitacaoCompletaRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event SolicitacaoCompletaRowChangeEventHandler SolicitacaoCompletaRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event SolicitacaoCompletaRowChangeEventHandler SolicitacaoCompletaRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddSolicitacaoCompletaRow(SolicitacaoCompletaRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaRow AddSolicitacaoCompletaRow(
                        string Cod_Produto, 
                        string Nome_Produto, 
                        string Quantidade_Solicitada, 
                        string Unidade_De_Medida, 
                        string Preco_Unitario, 
                        string Data_Emissao, 
                        string Periodo_Solicitacao, 
                        string Periodo_Entrega, 
                        string Condicao_Pagamento, 
                        string Total, 
                        string NomeFornecedor, 
                        string CPFFornecedor, 
                        string CEPFornecedor, 
                        string EnderecoFornecedor, 
                        string BairroFornecedor, 
                        string CidadeFornecedor, 
                        string ComplementoFornecedor, 
                        string EstadoFornecedor, 
                        string Complemento2Fornecedor, 
                        string NumeroFornecedor, 
                        string TelefoneFornecedor, 
                        string Telefone2Fornecedor, 
                        string EmailFornecedor) {
                SolicitacaoCompletaRow rowSolicitacaoCompletaRow = ((SolicitacaoCompletaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Cod_Produto,
                        Nome_Produto,
                        Quantidade_Solicitada,
                        Unidade_De_Medida,
                        Preco_Unitario,
                        Data_Emissao,
                        Periodo_Solicitacao,
                        Periodo_Entrega,
                        Condicao_Pagamento,
                        Total,
                        NomeFornecedor,
                        CPFFornecedor,
                        CEPFornecedor,
                        EnderecoFornecedor,
                        BairroFornecedor,
                        CidadeFornecedor,
                        ComplementoFornecedor,
                        EstadoFornecedor,
                        Complemento2Fornecedor,
                        NumeroFornecedor,
                        TelefoneFornecedor,
                        Telefone2Fornecedor,
                        EmailFornecedor};
                rowSolicitacaoCompletaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowSolicitacaoCompletaRow);
                return rowSolicitacaoCompletaRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                SolicitacaoCompletaDataTable cln = ((SolicitacaoCompletaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SolicitacaoCompletaDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnCod_Produto = base.Columns["Cod_Produto"];
                this.columnNome_Produto = base.Columns["Nome_Produto"];
                this.columnQuantidade_Solicitada = base.Columns["Quantidade_Solicitada"];
                this.columnUnidade_De_Medida = base.Columns["Unidade_De_Medida"];
                this.columnPreco_Unitario = base.Columns["Preco_Unitario"];
                this.columnData_Emissao = base.Columns["Data_Emissao"];
                this.columnPeriodo_Solicitacao = base.Columns["Periodo_Solicitacao"];
                this.columnPeriodo_Entrega = base.Columns["Periodo_Entrega"];
                this.columnCondicao_Pagamento = base.Columns["Condicao_Pagamento"];
                this.columnTotal = base.Columns["Total"];
                this.columnNomeFornecedor = base.Columns["NomeFornecedor"];
                this.columnCPFFornecedor = base.Columns["CPFFornecedor"];
                this.columnCEPFornecedor = base.Columns["CEPFornecedor"];
                this.columnEnderecoFornecedor = base.Columns["EnderecoFornecedor"];
                this.columnBairroFornecedor = base.Columns["BairroFornecedor"];
                this.columnCidadeFornecedor = base.Columns["CidadeFornecedor"];
                this.columnComplementoFornecedor = base.Columns["ComplementoFornecedor"];
                this.columnEstadoFornecedor = base.Columns["EstadoFornecedor"];
                this.columnComplemento2Fornecedor = base.Columns["Complemento2Fornecedor"];
                this.columnNumeroFornecedor = base.Columns["NumeroFornecedor"];
                this.columnTelefoneFornecedor = base.Columns["TelefoneFornecedor"];
                this.columnTelefone2Fornecedor = base.Columns["Telefone2Fornecedor"];
                this.columnEmailFornecedor = base.Columns["EmailFornecedor"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnCod_Produto = new global::System.Data.DataColumn("Cod_Produto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Produto);
                this.columnNome_Produto = new global::System.Data.DataColumn("Nome_Produto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNome_Produto);
                this.columnQuantidade_Solicitada = new global::System.Data.DataColumn("Quantidade_Solicitada", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQuantidade_Solicitada);
                this.columnUnidade_De_Medida = new global::System.Data.DataColumn("Unidade_De_Medida", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnidade_De_Medida);
                this.columnPreco_Unitario = new global::System.Data.DataColumn("Preco_Unitario", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPreco_Unitario);
                this.columnData_Emissao = new global::System.Data.DataColumn("Data_Emissao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnData_Emissao);
                this.columnPeriodo_Solicitacao = new global::System.Data.DataColumn("Periodo_Solicitacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPeriodo_Solicitacao);
                this.columnPeriodo_Entrega = new global::System.Data.DataColumn("Periodo_Entrega", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPeriodo_Entrega);
                this.columnCondicao_Pagamento = new global::System.Data.DataColumn("Condicao_Pagamento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCondicao_Pagamento);
                this.columnTotal = new global::System.Data.DataColumn("Total", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotal);
                this.columnNomeFornecedor = new global::System.Data.DataColumn("NomeFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomeFornecedor);
                this.columnCPFFornecedor = new global::System.Data.DataColumn("CPFFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCPFFornecedor);
                this.columnCEPFornecedor = new global::System.Data.DataColumn("CEPFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCEPFornecedor);
                this.columnEnderecoFornecedor = new global::System.Data.DataColumn("EnderecoFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEnderecoFornecedor);
                this.columnBairroFornecedor = new global::System.Data.DataColumn("BairroFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBairroFornecedor);
                this.columnCidadeFornecedor = new global::System.Data.DataColumn("CidadeFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCidadeFornecedor);
                this.columnComplementoFornecedor = new global::System.Data.DataColumn("ComplementoFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnComplementoFornecedor);
                this.columnEstadoFornecedor = new global::System.Data.DataColumn("EstadoFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEstadoFornecedor);
                this.columnComplemento2Fornecedor = new global::System.Data.DataColumn("Complemento2Fornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnComplemento2Fornecedor);
                this.columnNumeroFornecedor = new global::System.Data.DataColumn("NumeroFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumeroFornecedor);
                this.columnTelefoneFornecedor = new global::System.Data.DataColumn("TelefoneFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefoneFornecedor);
                this.columnTelefone2Fornecedor = new global::System.Data.DataColumn("Telefone2Fornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefone2Fornecedor);
                this.columnEmailFornecedor = new global::System.Data.DataColumn("EmailFornecedor", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEmailFornecedor);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaRow NewSolicitacaoCompletaRow() {
                return ((SolicitacaoCompletaRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SolicitacaoCompletaRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(SolicitacaoCompletaRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SolicitacaoCompletaRowChanged != null)) {
                    this.SolicitacaoCompletaRowChanged(this, new SolicitacaoCompletaRowChangeEvent(((SolicitacaoCompletaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SolicitacaoCompletaRowChanging != null)) {
                    this.SolicitacaoCompletaRowChanging(this, new SolicitacaoCompletaRowChangeEvent(((SolicitacaoCompletaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SolicitacaoCompletaRowDeleted != null)) {
                    this.SolicitacaoCompletaRowDeleted(this, new SolicitacaoCompletaRowChangeEvent(((SolicitacaoCompletaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SolicitacaoCompletaRowDeleting != null)) {
                    this.SolicitacaoCompletaRowDeleting(this, new SolicitacaoCompletaRowChangeEvent(((SolicitacaoCompletaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveSolicitacaoCompletaRow(SolicitacaoCompletaRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsSolicitacaoCompraCompleta ds = new dsSolicitacaoCompraCompleta();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SolicitacaoCompletaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class SolicitacaoCompletaRow : global::System.Data.DataRow {
            
            private SolicitacaoCompletaDataTable tableSolicitacaoCompleta;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal SolicitacaoCompletaRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSolicitacaoCompleta = ((SolicitacaoCompletaDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Cod_Produto {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Cod_ProdutoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cod_Produto\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Cod_ProdutoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Nome_Produto {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Nome_ProdutoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Nome_Produto\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Nome_ProdutoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Quantidade_Solicitada {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Quantidade_SolicitadaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Quantidade_Solicitada\' in table \'SolicitacaoCompleta\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Quantidade_SolicitadaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Unidade_De_Medida {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Unidade_De_MedidaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Unidade_De_Medida\' in table \'SolicitacaoCompleta\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Unidade_De_MedidaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Preco_Unitario {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Preco_UnitarioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Preco_Unitario\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Preco_UnitarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Data_Emissao {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Data_EmissaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Data_Emissao\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Data_EmissaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Periodo_Solicitacao {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Periodo_SolicitacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Periodo_Solicitacao\' in table \'SolicitacaoCompleta\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Periodo_SolicitacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Periodo_Entrega {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Periodo_EntregaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Periodo_Entrega\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Periodo_EntregaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Condicao_Pagamento {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Condicao_PagamentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Condicao_Pagamento\' in table \'SolicitacaoCompleta\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Condicao_PagamentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Total {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.TotalColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Total\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.TotalColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NomeFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.NomeFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomeFornecedor\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.NomeFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CPFFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.CPFFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CPFFornecedor\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.CPFFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CEPFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.CEPFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CEPFornecedor\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.CEPFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string EnderecoFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.EnderecoFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EnderecoFornecedor\' in table \'SolicitacaoCompleta\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.EnderecoFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string BairroFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.BairroFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BairroFornecedor\' in table \'SolicitacaoCompleta\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.BairroFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string CidadeFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.CidadeFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CidadeFornecedor\' in table \'SolicitacaoCompleta\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.CidadeFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ComplementoFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.ComplementoFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ComplementoFornecedor\' in table \'SolicitacaoCompleta\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.ComplementoFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string EstadoFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.EstadoFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EstadoFornecedor\' in table \'SolicitacaoCompleta\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.EstadoFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Complemento2Fornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Complemento2FornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Complemento2Fornecedor\' in table \'SolicitacaoCompleta\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Complemento2FornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NumeroFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.NumeroFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NumeroFornecedor\' in table \'SolicitacaoCompleta\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.NumeroFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TelefoneFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.TelefoneFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TelefoneFornecedor\' in table \'SolicitacaoCompleta\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.TelefoneFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string Telefone2Fornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.Telefone2FornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Telefone2Fornecedor\' in table \'SolicitacaoCompleta\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.Telefone2FornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string EmailFornecedor {
                get {
                    try {
                        return ((string)(this[this.tableSolicitacaoCompleta.EmailFornecedorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EmailFornecedor\' in table \'SolicitacaoCompleta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSolicitacaoCompleta.EmailFornecedorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCod_ProdutoNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Cod_ProdutoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCod_ProdutoNull() {
                this[this.tableSolicitacaoCompleta.Cod_ProdutoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNome_ProdutoNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Nome_ProdutoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNome_ProdutoNull() {
                this[this.tableSolicitacaoCompleta.Nome_ProdutoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsQuantidade_SolicitadaNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Quantidade_SolicitadaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetQuantidade_SolicitadaNull() {
                this[this.tableSolicitacaoCompleta.Quantidade_SolicitadaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUnidade_De_MedidaNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Unidade_De_MedidaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUnidade_De_MedidaNull() {
                this[this.tableSolicitacaoCompleta.Unidade_De_MedidaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPreco_UnitarioNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Preco_UnitarioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPreco_UnitarioNull() {
                this[this.tableSolicitacaoCompleta.Preco_UnitarioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsData_EmissaoNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Data_EmissaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetData_EmissaoNull() {
                this[this.tableSolicitacaoCompleta.Data_EmissaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPeriodo_SolicitacaoNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Periodo_SolicitacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPeriodo_SolicitacaoNull() {
                this[this.tableSolicitacaoCompleta.Periodo_SolicitacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPeriodo_EntregaNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Periodo_EntregaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPeriodo_EntregaNull() {
                this[this.tableSolicitacaoCompleta.Periodo_EntregaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCondicao_PagamentoNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Condicao_PagamentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCondicao_PagamentoNull() {
                this[this.tableSolicitacaoCompleta.Condicao_PagamentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTotalNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.TotalColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTotalNull() {
                this[this.tableSolicitacaoCompleta.TotalColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNomeFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.NomeFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNomeFornecedorNull() {
                this[this.tableSolicitacaoCompleta.NomeFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCPFFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.CPFFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCPFFornecedorNull() {
                this[this.tableSolicitacaoCompleta.CPFFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCEPFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.CEPFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCEPFornecedorNull() {
                this[this.tableSolicitacaoCompleta.CEPFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsEnderecoFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.EnderecoFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetEnderecoFornecedorNull() {
                this[this.tableSolicitacaoCompleta.EnderecoFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsBairroFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.BairroFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetBairroFornecedorNull() {
                this[this.tableSolicitacaoCompleta.BairroFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsCidadeFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.CidadeFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetCidadeFornecedorNull() {
                this[this.tableSolicitacaoCompleta.CidadeFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsComplementoFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.ComplementoFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetComplementoFornecedorNull() {
                this[this.tableSolicitacaoCompleta.ComplementoFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsEstadoFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.EstadoFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetEstadoFornecedorNull() {
                this[this.tableSolicitacaoCompleta.EstadoFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsComplemento2FornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Complemento2FornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetComplemento2FornecedorNull() {
                this[this.tableSolicitacaoCompleta.Complemento2FornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNumeroFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.NumeroFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNumeroFornecedorNull() {
                this[this.tableSolicitacaoCompleta.NumeroFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTelefoneFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.TelefoneFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTelefoneFornecedorNull() {
                this[this.tableSolicitacaoCompleta.TelefoneFornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTelefone2FornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.Telefone2FornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTelefone2FornecedorNull() {
                this[this.tableSolicitacaoCompleta.Telefone2FornecedorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsEmailFornecedorNull() {
                return this.IsNull(this.tableSolicitacaoCompleta.EmailFornecedorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetEmailFornecedorNull() {
                this[this.tableSolicitacaoCompleta.EmailFornecedorColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class SolicitacaoCompletaRowChangeEvent : global::System.EventArgs {
            
            private SolicitacaoCompletaRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaRowChangeEvent(SolicitacaoCompletaRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public SolicitacaoCompletaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591