//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp3.localhostCmp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ComprasSoap", Namespace="http://tempuri.org/")]
    public partial class Compras : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GravarOrcamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastroFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArquivarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarGerarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarSolicitacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaSolicitacaoItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaSolicitacaoDeCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaComboFornecedorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Compras() {
            this.Url = global::WindowsFormsApp3.Properties.Settings.Default.WindowsFormsApp3_localhostCmp_Compras;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GravarOrcamentoCompletedEventHandler GravarOrcamentoCompleted;
        
        /// <remarks/>
        public event CadastroFornecedorCompletedEventHandler CadastroFornecedorCompleted;
        
        /// <remarks/>
        public event ArquivarCompletedEventHandler ArquivarCompleted;
        
        /// <remarks/>
        public event AtualizarCompletedEventHandler AtualizarCompleted;
        
        /// <remarks/>
        public event AtualizarGerarCompletedEventHandler AtualizarGerarCompleted;
        
        /// <remarks/>
        public event RetornarSolicitacaoCompletedEventHandler RetornarSolicitacaoCompleted;
        
        /// <remarks/>
        public event RetornaSolicitacaoItemCompletedEventHandler RetornaSolicitacaoItemCompleted;
        
        /// <remarks/>
        public event RetornaSolicitacaoDeCompraCompletedEventHandler RetornaSolicitacaoDeCompraCompleted;
        
        /// <remarks/>
        public event RetornaFornecedorCompletedEventHandler RetornaFornecedorCompleted;
        
        /// <remarks/>
        public event RetornaComboFornecedorCompletedEventHandler RetornaComboFornecedorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarOrcamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GravarOrcamento(int IdPedido, string Tipo, string DataEmissao, string Observacoes, string Vendedor, string PrazoEntrega, string CondicaoPag, double ValorAdicional, double Valor, int QtdItens) {
            object[] results = this.Invoke("GravarOrcamento", new object[] {
                        IdPedido,
                        Tipo,
                        DataEmissao,
                        Observacoes,
                        Vendedor,
                        PrazoEntrega,
                        CondicaoPag,
                        ValorAdicional,
                        Valor,
                        QtdItens});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GravarOrcamentoAsync(int IdPedido, string Tipo, string DataEmissao, string Observacoes, string Vendedor, string PrazoEntrega, string CondicaoPag, double ValorAdicional, double Valor, int QtdItens) {
            this.GravarOrcamentoAsync(IdPedido, Tipo, DataEmissao, Observacoes, Vendedor, PrazoEntrega, CondicaoPag, ValorAdicional, Valor, QtdItens, null);
        }
        
        /// <remarks/>
        public void GravarOrcamentoAsync(int IdPedido, string Tipo, string DataEmissao, string Observacoes, string Vendedor, string PrazoEntrega, string CondicaoPag, double ValorAdicional, double Valor, int QtdItens, object userState) {
            if ((this.GravarOrcamentoOperationCompleted == null)) {
                this.GravarOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarOrcamentoOperationCompleted);
            }
            this.InvokeAsync("GravarOrcamento", new object[] {
                        IdPedido,
                        Tipo,
                        DataEmissao,
                        Observacoes,
                        Vendedor,
                        PrazoEntrega,
                        CondicaoPag,
                        ValorAdicional,
                        Valor,
                        QtdItens}, this.GravarOrcamentoOperationCompleted, userState);
        }
        
        private void OnGravarOrcamentoOperationCompleted(object arg) {
            if ((this.GravarOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarOrcamentoCompleted(this, new GravarOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastroFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastroFornecedor(string Nome, string CPF, string CEP, string Endereco, string Bairro, string Cidade, string Complemento, string Estado, string Complemento2, string Numero, string Telefone, string Telefone2, string EMAIL) {
            object[] results = this.Invoke("CadastroFornecedor", new object[] {
                        Nome,
                        CPF,
                        CEP,
                        Endereco,
                        Bairro,
                        Cidade,
                        Complemento,
                        Estado,
                        Complemento2,
                        Numero,
                        Telefone,
                        Telefone2,
                        EMAIL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastroFornecedorAsync(string Nome, string CPF, string CEP, string Endereco, string Bairro, string Cidade, string Complemento, string Estado, string Complemento2, string Numero, string Telefone, string Telefone2, string EMAIL) {
            this.CadastroFornecedorAsync(Nome, CPF, CEP, Endereco, Bairro, Cidade, Complemento, Estado, Complemento2, Numero, Telefone, Telefone2, EMAIL, null);
        }
        
        /// <remarks/>
        public void CadastroFornecedorAsync(string Nome, string CPF, string CEP, string Endereco, string Bairro, string Cidade, string Complemento, string Estado, string Complemento2, string Numero, string Telefone, string Telefone2, string EMAIL, object userState) {
            if ((this.CadastroFornecedorOperationCompleted == null)) {
                this.CadastroFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastroFornecedorOperationCompleted);
            }
            this.InvokeAsync("CadastroFornecedor", new object[] {
                        Nome,
                        CPF,
                        CEP,
                        Endereco,
                        Bairro,
                        Cidade,
                        Complemento,
                        Estado,
                        Complemento2,
                        Numero,
                        Telefone,
                        Telefone2,
                        EMAIL}, this.CadastroFornecedorOperationCompleted, userState);
        }
        
        private void OnCadastroFornecedorOperationCompleted(object arg) {
            if ((this.CadastroFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastroFornecedorCompleted(this, new CadastroFornecedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Arquivar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Arquivar(int IdPedido) {
            object[] results = this.Invoke("Arquivar", new object[] {
                        IdPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ArquivarAsync(int IdPedido) {
            this.ArquivarAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void ArquivarAsync(int IdPedido, object userState) {
            if ((this.ArquivarOperationCompleted == null)) {
                this.ArquivarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArquivarOperationCompleted);
            }
            this.InvokeAsync("Arquivar", new object[] {
                        IdPedido}, this.ArquivarOperationCompleted, userState);
        }
        
        private void OnArquivarOperationCompleted(object arg) {
            if ((this.ArquivarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArquivarCompleted(this, new ArquivarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Atualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Atualizar(int IdPedido) {
            object[] results = this.Invoke("Atualizar", new object[] {
                        IdPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarAsync(int IdPedido) {
            this.AtualizarAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void AtualizarAsync(int IdPedido, object userState) {
            if ((this.AtualizarOperationCompleted == null)) {
                this.AtualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarOperationCompleted);
            }
            this.InvokeAsync("Atualizar", new object[] {
                        IdPedido}, this.AtualizarOperationCompleted, userState);
        }
        
        private void OnAtualizarOperationCompleted(object arg) {
            if ((this.AtualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarCompleted(this, new AtualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtualizarGerar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AtualizarGerar(int IdPedido) {
            object[] results = this.Invoke("AtualizarGerar", new object[] {
                        IdPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarGerarAsync(int IdPedido) {
            this.AtualizarGerarAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void AtualizarGerarAsync(int IdPedido, object userState) {
            if ((this.AtualizarGerarOperationCompleted == null)) {
                this.AtualizarGerarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarGerarOperationCompleted);
            }
            this.InvokeAsync("AtualizarGerar", new object[] {
                        IdPedido}, this.AtualizarGerarOperationCompleted, userState);
        }
        
        private void OnAtualizarGerarOperationCompleted(object arg) {
            if ((this.AtualizarGerarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarGerarCompleted(this, new AtualizarGerarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarSolicitacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaSolicitacao", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SOLICITACAO", IsNullable=false)]
        public Solicitacao[] RetornarSolicitacao() {
            object[] results = this.Invoke("RetornarSolicitacao", new object[0]);
            return ((Solicitacao[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornarSolicitacaoAsync() {
            this.RetornarSolicitacaoAsync(null);
        }
        
        /// <remarks/>
        public void RetornarSolicitacaoAsync(object userState) {
            if ((this.RetornarSolicitacaoOperationCompleted == null)) {
                this.RetornarSolicitacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarSolicitacaoOperationCompleted);
            }
            this.InvokeAsync("RetornarSolicitacao", new object[0], this.RetornarSolicitacaoOperationCompleted, userState);
        }
        
        private void OnRetornarSolicitacaoOperationCompleted(object arg) {
            if ((this.RetornarSolicitacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarSolicitacaoCompleted(this, new RetornarSolicitacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaSolicitacaoItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaSolicitacaoItem", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ITEMSOLICITACAO", IsNullable=false)]
        public SolicitacaoItem[] RetornaSolicitacaoItem(int IdPedido) {
            object[] results = this.Invoke("RetornaSolicitacaoItem", new object[] {
                        IdPedido});
            return ((SolicitacaoItem[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaSolicitacaoItemAsync(int IdPedido) {
            this.RetornaSolicitacaoItemAsync(IdPedido, null);
        }
        
        /// <remarks/>
        public void RetornaSolicitacaoItemAsync(int IdPedido, object userState) {
            if ((this.RetornaSolicitacaoItemOperationCompleted == null)) {
                this.RetornaSolicitacaoItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaSolicitacaoItemOperationCompleted);
            }
            this.InvokeAsync("RetornaSolicitacaoItem", new object[] {
                        IdPedido}, this.RetornaSolicitacaoItemOperationCompleted, userState);
        }
        
        private void OnRetornaSolicitacaoItemOperationCompleted(object arg) {
            if ((this.RetornaSolicitacaoItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaSolicitacaoItemCompleted(this, new RetornaSolicitacaoItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaSolicitacaoDeCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaSolicitacoes", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SOLICITACOES", IsNullable=false)]
        public Solicitacoes[] RetornaSolicitacaoDeCompra() {
            object[] results = this.Invoke("RetornaSolicitacaoDeCompra", new object[0]);
            return ((Solicitacoes[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaSolicitacaoDeCompraAsync() {
            this.RetornaSolicitacaoDeCompraAsync(null);
        }
        
        /// <remarks/>
        public void RetornaSolicitacaoDeCompraAsync(object userState) {
            if ((this.RetornaSolicitacaoDeCompraOperationCompleted == null)) {
                this.RetornaSolicitacaoDeCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaSolicitacaoDeCompraOperationCompleted);
            }
            this.InvokeAsync("RetornaSolicitacaoDeCompra", new object[0], this.RetornaSolicitacaoDeCompraOperationCompleted, userState);
        }
        
        private void OnRetornaSolicitacaoDeCompraOperationCompleted(object arg) {
            if ((this.RetornaSolicitacaoDeCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaSolicitacaoDeCompraCompleted(this, new RetornaSolicitacaoDeCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaFornecedor", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("FORNECEDOR", IsNullable=false)]
        public Fornecedor[] RetornaFornecedor() {
            object[] results = this.Invoke("RetornaFornecedor", new object[0]);
            return ((Fornecedor[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaFornecedorAsync() {
            this.RetornaFornecedorAsync(null);
        }
        
        /// <remarks/>
        public void RetornaFornecedorAsync(object userState) {
            if ((this.RetornaFornecedorOperationCompleted == null)) {
                this.RetornaFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaFornecedorOperationCompleted);
            }
            this.InvokeAsync("RetornaFornecedor", new object[0], this.RetornaFornecedorOperationCompleted, userState);
        }
        
        private void OnRetornaFornecedorOperationCompleted(object arg) {
            if ((this.RetornaFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaFornecedorCompleted(this, new RetornaFornecedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaComboFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscaComboFornecedor", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("FORNECEDOR", IsNullable=false)]
        public FornecedorCombo[] RetornaComboFornecedor() {
            object[] results = this.Invoke("RetornaComboFornecedor", new object[0]);
            return ((FornecedorCombo[])(results[0]));
        }
        
        /// <remarks/>
        public void RetornaComboFornecedorAsync() {
            this.RetornaComboFornecedorAsync(null);
        }
        
        /// <remarks/>
        public void RetornaComboFornecedorAsync(object userState) {
            if ((this.RetornaComboFornecedorOperationCompleted == null)) {
                this.RetornaComboFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaComboFornecedorOperationCompleted);
            }
            this.InvokeAsync("RetornaComboFornecedor", new object[0], this.RetornaComboFornecedorOperationCompleted, userState);
        }
        
        private void OnRetornaComboFornecedorOperationCompleted(object arg) {
            if ((this.RetornaComboFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaComboFornecedorCompleted(this, new RetornaComboFornecedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Solicitacao {
        
        private int idPedidoField;
        
        private string solicitanteField;
        
        private string urgenciaField;
        
        private string motivoField;
        
        private string dataCriacaoField;
        
        private string tipoField;
        
        private double valorField;
        
        /// <remarks/>
        public int IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Solicitante {
            get {
                return this.solicitanteField;
            }
            set {
                this.solicitanteField = value;
            }
        }
        
        /// <remarks/>
        public string Urgencia {
            get {
                return this.urgenciaField;
            }
            set {
                this.urgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public double Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FornecedorCombo {
        
        private int idField;
        
        private string nomeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fornecedor {
        
        private string nomeField;
        
        private string cPFField;
        
        private string estadoField;
        
        private string cEPField;
        
        private string telefoneField;
        
        private string emailField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Solicitacoes {
        
        private int idPedidoField;
        
        private string solicitanteField;
        
        private string urgenciaField;
        
        private string dataCriacaoField;
        
        private string tipoField;
        
        private string statusField;
        
        /// <remarks/>
        public int IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Solicitante {
            get {
                return this.solicitanteField;
            }
            set {
                this.solicitanteField = value;
            }
        }
        
        /// <remarks/>
        public string Urgencia {
            get {
                return this.urgenciaField;
            }
            set {
                this.urgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitacaoItem {
        
        private string codField;
        
        private string nomeField;
        
        private string unidadeMedidaField;
        
        private double qtdEstoqueField;
        
        private double qtdMinimaField;
        
        private double qtdMaximaField;
        
        private double solicitarField;
        
        /// <remarks/>
        public string Cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string UnidadeMedida {
            get {
                return this.unidadeMedidaField;
            }
            set {
                this.unidadeMedidaField = value;
            }
        }
        
        /// <remarks/>
        public double QtdEstoque {
            get {
                return this.qtdEstoqueField;
            }
            set {
                this.qtdEstoqueField = value;
            }
        }
        
        /// <remarks/>
        public double QtdMinima {
            get {
                return this.qtdMinimaField;
            }
            set {
                this.qtdMinimaField = value;
            }
        }
        
        /// <remarks/>
        public double QtdMaxima {
            get {
                return this.qtdMaximaField;
            }
            set {
                this.qtdMaximaField = value;
            }
        }
        
        /// <remarks/>
        public double Solicitar {
            get {
                return this.solicitarField;
            }
            set {
                this.solicitarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GravarOrcamentoCompletedEventHandler(object sender, GravarOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CadastroFornecedorCompletedEventHandler(object sender, CadastroFornecedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastroFornecedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastroFornecedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ArquivarCompletedEventHandler(object sender, ArquivarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArquivarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArquivarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AtualizarCompletedEventHandler(object sender, AtualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AtualizarGerarCompletedEventHandler(object sender, AtualizarGerarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarGerarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarGerarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornarSolicitacaoCompletedEventHandler(object sender, RetornarSolicitacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarSolicitacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarSolicitacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Solicitacao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Solicitacao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaSolicitacaoItemCompletedEventHandler(object sender, RetornaSolicitacaoItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaSolicitacaoItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaSolicitacaoItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SolicitacaoItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SolicitacaoItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaSolicitacaoDeCompraCompletedEventHandler(object sender, RetornaSolicitacaoDeCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaSolicitacaoDeCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaSolicitacaoDeCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Solicitacoes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Solicitacoes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaFornecedorCompletedEventHandler(object sender, RetornaFornecedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaFornecedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaFornecedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Fornecedor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Fornecedor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetornaComboFornecedorCompletedEventHandler(object sender, RetornaComboFornecedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaComboFornecedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaComboFornecedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FornecedorCombo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FornecedorCombo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591